name: 'ğŸ”§ Checks'

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    name: 'Checks'
    timeout-minutes: 4
    runs-on: ['ubuntu-latest']
    steps:
      - name: 'ğŸ”‘ Checkout'
        uses: actions/checkout@v6

      - name: 'ğŸ° Setup Bun'
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: 'Install Dependencies'
        run: bun install --frozen-lockfile

      - name: 'Setup Biome'
        uses: biomejs/setup-biome@main
        with:
          version: 'latest'

      - name: 'Lint & Format'
        run: biome ci .

      - name: 'Typecheck'
        run: bun tsgo --project tsconfig.json --noEmit

      - name: 'Build Worker & Workspaces'
        run: bun run build